### ISSUE TITLE
nuxt not work component

### ISSUE THREAD

**Issue by solinad21** [darrenjennings/vue-autosuggest#166] opened 2020-01-13 07:45 UTC
Use 
Nuxt 2.11.0 in SSR mode
Node 10.16.3
NPM 6.9.0

Always when I click on the component it shows me all the suggestions and when I write some characters it doesn't generate any suggestions as if it didn't work.  

- annex an image -

![nuxt-vue-autosuggest-no-work-2](https://user-images.githubusercontent.com/1120174/72239514-7dce5300-359e-11ea-9fa3-343a48eedf88.jpg)

![nuxt-vue-autosuggest-no-work](https://user-images.githubusercontent.com/1120174/72239343-fb459380-359d-11ea-843e-e859ce33d72e.jpg)

**Comment by darrenjennings** [comment] 2020-01-13 14:22
@solinad21 can you reproduce with a codesandbox? https://codesandbox.io/s/

**Comment by darrenjennings** [comment] 2020-02-10 20:35
closing since the error is unclear and there is no reproduction link

**Closed as completed by darrenjennings** 2020-02-10 20:35 UTC

**Comment by mahiraltinkaya** [comment] 2021-01-07 10:17
Hi, 
i have same problem for this package. I am using in Nuxt  SSR mode . I cant see any css maybe need a css code but i cant see anywhere. Can you help me ?
Nuxt: 2.14.6


Create a Plugin
![image](https://user-images.githubusercontent.com/25014707/103880661-7e82c200-50ea-11eb-8e8c-6f10d4b94422.png)

Insert Plugin
![image](https://user-images.githubusercontent.com/25014707/103880693-893d5700-50ea-11eb-89ff-c8f1b2d49ba0.png)

Plugin Result
![image](https://user-images.githubusercontent.com/25014707/103880743-99553680-50ea-11eb-9359-3b1aa5667bcd.png)


on template
![image](https://user-images.githubusercontent.com/25014707/103880976-e2a58600-50ea-11eb-8181-e4b97cc7d165.png)

**Comment by darrenjennings** [comment] 2021-01-07 13:47
@mahiraltinkaya this component does not come with any css, you have to write your own.
