### ISSUE TITLE
Mobile Issue | spinner does not showing

### ISSUE THREAD

**Issue by ahsansalaldaha** [darrenjennings/vue-autosuggest#106] opened 2019-04-23 11:08 UTC
- `vue-autosuggest` version: 1.8.3
- `node` version: v8.11.2
- `npm` (or `yarn`) version: 5.6.0

What you did:
Implemented auto suggest in my project. working flawlessly except mobile.

What happened:

Spinner not showing after typing

Problem description:
Does not show the spinning after a user typed something unless he taps out of the field.

Suggested solution:
not sure

**Comment by darrenjennings** [comment] 2019-04-23 20:03
@ahsansalaldaha there is no "spinner" bundled with vue-autosuggest so not sure what you mean. Can you please create a codesandbox to reproduce your issue? 

You can fork this one: https://codesandbox.io/s/627qlx66oz

**Comment by rangermeier** [comment] 2019-04-24 10:10
Not sure about the spinner (I guess some custom UI), but I can confirm that `on-input-change` does not fire on Chrome Android 73 while the input has focus. Only when the input loses focus `on-input-change` triggers. It works on Firefox Android though.

E.g. I use `on-input-change` to fetch search results from the backend while the user types. On Chrome Android the suggestions will only update after I click elsewhere on the page (then the event fires) and then focus the input again (the suggestions are shown).

You can test it with the official  [demo](https://darrenjennings.github.io/vue-autosuggest/storybook/?selectedKind=Vue-Autosuggest&selectedStory=simplest&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by rangermeier** [comment] 2019-04-24 10:58
Some more insights: This is caused by https://github.com/vuejs/vue/issues/9777#issuecomment-478831263

On some mobile phones the keyboard is in _composing_ mode while typing a word, which prevents v-model to fire.

If we want to get notified after each keystroke we'd have to use `<input v-on:input="e => searchInput e.target.value" :value="searhcInput" />`.

Not 100% sure as I don't have any experience with languages that use composition but I assume eager updating would be generally the desired behavior for an autosuggest widget.

**Comment by ahsansalaldaha** [comment] 2019-04-24 11:25
Thank you so much Rupert for the kind information.

**Comment by darrenjennings** [comment] 2019-04-24 23:55
This seems like a duplicate of https://github.com/darrenjennings/vue-autosuggest/issues/70. Please try beta version (which is very stable, just working on some more things before I release as `2.0` officially):

```bash
npm install vue-autosuggest@2.0.0-beta.7
``` 

this version removes internal v-model in favor of `@input` and `:value` as @rangermeier points out. Hopefully this helps:
https://codesandbox.io/s/2vr87nyvkp

**Closed as completed** 2019-04-29 15:36 UTC
