### ISSUE TITLE
If i want use vee-validate with this, how can i do 

### ISSUE THREAD

**Issue by EtheriousNatsu** [darrenjennings/vue-autosuggest#72] opened 2018-10-25 02:50 UTC
- `vue-autosuggest` version:1.7.1-2
- `node` version:10.3.0
- `npm` (or `yarn`) version:6.1.0

Relevant code or config

```html
<input
    name="testName"
    data-vv-as="test name"
     v-validate="'required'"
     data-vv-validate-on="input" />
```

What you did:
I want use vee-validate work on this component, how should i do?

What happened:

Reproduction repository:

Problem description:
I dont know how to use vee-validate on this component.

Suggested solution:

**Comment by darrenjennings** [comment] 2018-10-25 06:36
You can find the vee validate example link in the readme: https://github.com/Educents/vue-autosuggest#examples

Duplicate of https://github.com/Educents/vue-autosuggest/issues/42

**Closed as completed by darrenjennings** 2018-10-25 06:36 UTC
Labels: duplicate

**Comment by EtheriousNatsu** [comment] 2018-10-25 07:20
thankyou, i will try
