### ISSUE TITLE
Is it possible to set initial-value after the component is initialized?

### ISSUE THREAD

**Issue by wujekbogdan** [darrenjennings/vue-autosuggest#95] opened 2019-02-24 19:13 UTC
I'd like to set the `initial-value` but the source of the value is asynchronous, so I need to do it after the vue-autosuggest component is initialized. I've looked at the source code and it seems that the initial value is set when the component is created so it's not reactive. The only way I found is to access the input element via ref... which doesn't seem very elegant.

Is there any better way of changing the input's value after the component is initialized?

**Comment by darrenjennings** [comment] 2019-02-24 21:38
@wujekbogdan yes! this is something I fixed in 2.0. I would recommend upgrading to the latest beta https://www.npmjs.com/package/vue-autosuggest/v/2.0.0-beta.6 which would give you `v-model` support, removes `initialValue` entirely, and thus gives you a way to programmatically control the value. If that sounds daunting, you can always just throw a `v-if` on the component and wait for the `initialValue` to be available. This is less than ideal because users won't see the component until the value is ready, so would recommend upgrading.

**Closed as completed by darrenjennings** 2019-02-24 21:38 UTC

**Comment by wujekbogdan** [comment] 2019-02-24 22:42
@darrenjennings 
Thanks! And also thanks for the `vue-autosuggest` component. It does exactly what I need, it's simple, flexible, and what's most important for me - it doesn't load its own CSS (which is not very common in Vue-world!).

**Comment by puremana** [comment] 2019-05-22 23:44
It worked to v-model, but broke my `shouldRenderSuggestions()` setup and `this.$refs.autosuggest.loading` values for some reason.

**Comment by darrenjennings** [comment] 2019-05-23 03:42
@puremana happy to help if you have a codesandbox for reproducing.

Fork this one for 1.x: https://codesandbox.io/s/vueautosuggest-api-clicking-things-in-the-headerfooter-bzdrp
Fork this one if you're on the beta: https://codesandbox.io/s/x9z1lo20mo
